/**
 * Fish Species Data Configuration
 * Complete information about salmon and sturgeon species
 */

export interface FishSpecies {
  id: string;
  commonName: string;
  scientificName: string;
  englishName: string;
  route: string;
  image: string;
  imageLarge: string;
  description: string;
  habitat: string;
  maxSize: string;
  maxWeight: string;
  lifespan: string;
  origin: string;
  value: string;
  nutrition: string;
  facts: string[];
  status: 'common' | 'rare' | 'endangered';
  category: 'salmon' | 'sturgeon';
}

export const salmonSpecies: FishSpecies[] = [
  {
    id: 'keta',
    commonName: 'Кета',
    scientificName: 'Oncorhynchus keta',
    englishName: 'Chum Salmon',
    route: '/species/keta',
    image: '/img/species/salmon/species/keta.jpg?v=2',
    imageLarge: '/img/species/salmon/species/keta.jpg?v=2',
    description: 'Самый популярный и ценный вид красной икры. Крупная рыба с высоким содержанием жира и белка.',
    habitat: 'Северная часть Тихого океана, реки Сахалина, Камчатки, Амура, Хоккайдо',
    maxSize: 'до 1 метра',
    maxWeight: 'до 15 кг',
    lifespan: '3-7 лет',
    origin: 'Эволюционировала из древних тихоокеанских лососей около 5-6 миллионов лет назад',
    value: 'Высокое содержание Омега-3 (до 2.8 г на 100г), белок (24-30 г), витамины D, B12. Икра крупная (5-7 мм)',
    nutrition: '250 ккал, 24г белка, 15г жира на 100г. Идеальна для детского питания',
    facts: [
      'Проходит до 4000 км вверх по рекам к местам нереста',
      'Меняет окраску на тигровые полосы в период нереста',
      'Икра кеты — самая крупная среди красных икр (5-7 мм)',
      'Может нереститься в пресной воде до 2 месяцев',
    ],
    status: 'common',
    category: 'salmon',
  },
  {
    id: 'gorbuscha',
    commonName: 'Горбуша',
    scientificName: 'Oncorhynchus gorbuscha',
    englishName: 'Pink Salmon',
    route: '/species/pink-salmon',
    image: '/img/species/salmon/species/pink-salmon.jpg?v=2',
    imageLarge: '/img/species/salmon/species/pink-salmon.jpg?v=2',
    description: 'Самый многочисленный и доступный вид тихоокеанских лососей. Небольшая, но быстрорастущая рыба.',
    habitat: 'Северная часть Тихого океана, прибрежные реки Сахалина, Камчатки, Курильских островов',
    maxSize: 'до 70 см',
    maxWeight: 'до 3 кг',
    lifespan: '2 года (самый короткий цикл)',
    origin: 'Произошла от общего предка тихоокеанских лососей, адаптировалась к короткому жизненному циклу',
    value: 'Доступная цена, быстрый рост. Икра среднего размера (4-5 мм), универсальна в кулинарии',
    nutrition: '140 ккал, 20г белка, 6г жира на 100г. Меньше жира, чем у кеты',
    facts: [
      'Единственный вид лососей с двухлетним жизненным циклом',
      'Самцы отращивают характерный горб на спине во время нереста',
      'Самый многочисленный промысловый лосось',
      'Не задерживается в пресной воде — сразу мигрирует в океан',
    ],
    status: 'common',
    category: 'salmon',
  },
  {
    id: 'nerka',
    commonName: 'Нерка',
    scientificName: 'Oncorhynchus nerka',
    englishName: 'Sockeye Salmon / Red Salmon',
    route: '/species/nerka',
    image: '/img/species/salmon/species/nerka.jpg?v=2',
    imageLarge: '/img/species/salmon/species/nerka.jpg?v=2',
    description: 'Красная рыба с ярко-красным мясом благодаря питанию ракообразными. Ценится за уникальный вкус.',
    habitat: 'Северная часть Тихого океана, озера Камчатки, Аляски, Британской Колумбии',
    maxSize: 'до 84 см',
    maxWeight: 'до 7 кг',
    lifespan: '4-6 лет',
    origin: 'Эволюционировала для нереста в озерах, что уникально среди лососей',
    value: 'Мясо ярко-красное из-за каротиноидов. Высокое содержание астаксантина — мощного антиоксиданта',
    nutrition: '180 ккал, 22г белка, 9г жира на 100г. Богата антиоксидантами',
    facts: [
      'Мясо ярко-красное благодаря питанию крилем и ракообразными',
      'Единственный лосось, который нерестится в озерах, а не реках',
      'Астаксантин в мясе — один из сильнейших антиоксидантов',
      'Может образовывать жилые формы (кокани) в озерах',
    ],
    status: 'common',
    category: 'salmon',
  },
  {
    id: 'chavycha',
    commonName: 'Чавыча',
    scientificName: 'Oncorhynchus tshawytscha',
    englishName: 'King Salmon / Chinook',
    route: '/species/chavycha',
    image: '/img/species/salmon/species/chavycha.jpg?v=2',
    imageLarge: '/img/species/salmon/species/chavycha.jpg?v=2',
    description: 'Крупнейший вид тихоокеанских лососей. Король среди лососей с самым жирным и нежным мясом.',
    habitat: 'Северная часть Тихого океана, крупные реки Аляски, Камчатки, Британской Колумбии',
    maxSize: 'до 1.5 метра',
    maxWeight: 'до 60 кг (рекорд 58 кг)',
    lifespan: '4-7 лет',
    origin: 'Древнейший вид тихоокеанских лососей, сохранивший максимальные размеры',
    value: 'Самое жирное и нежное мясо среди лососей. Премиальная икра. Высокая стоимость',
    nutrition: '231 ккал, 25г белка, 13г жира на 100г. Максимальное содержание Омега-3',
    facts: [
      'Крупнейший вид тихоокеанских лососей — может достигать 60 кг',
      'Самое жирное мясо среди всех лососей (до 13% жира)',
      'Рекордная рыба была поймана на Аляске — 58 кг',
      'Икра чавычи — одна из самых дорогих красных икр',
    ],
    status: 'rare',
    category: 'salmon',
  },
  {
    id: 'kizhuch',
    commonName: 'Кижуч',
    scientificName: 'Oncorhynchus kisutch',
    englishName: 'Coho Salmon / Silver Salmon',
    route: '/species/kizhuch',
    image: '/img/species/salmon/species/kizhuch.jpg?v=2',
    imageLarge: '/img/species/salmon/species/kizhuch.jpg?v=2',
    description: 'Серебристый лосось с нежным мясом. Агрессивный охотник, ценится за отличные вкусовые качества.',
    habitat: 'Северная часть Тихого океана, реки Дальнего Востока, Аляски, Калифорнии',
    maxSize: 'до 88 см',
    maxWeight: 'до 14 кг',
    lifespan: '3-4 года',
    origin: 'Эволюционировала для жизни в более теплых водах, чем другие лососи',
    value: 'Отличное мясо для стейков. Икра среднего размера с приятной упругостью',
    nutrition: '206 ккал, 23г белка, 12г жира на 100г. Сбалансированный состав',
    facts: [
      'Самый агрессивный охотник среди лососей',
      'Может преследовать добычу в открытом океане',
      'Отличная рыба для спортивной рыбалки',
      'Серебристая чешуя в океане, ярко-красная в период нереста',
    ],
    status: 'common',
    category: 'salmon',
  },
  {
    id: 'sima',
    commonName: 'Сима',
    scientificName: 'Oncorhynchus masou',
    englishName: 'Cherry Salmon / Masu Salmon',
    route: '/species/sima',
    image: '/img/species/salmon/species/sima.jpg?v=2',
    imageLarge: '/img/species/salmon/species/sima.jpg?v=2',
    description: 'Редкий азиатский вид с вишневым оттенком. Японская национальная рыба, охраняемый вид.',
    habitat: 'Реки Японии, Кореи, Приморья, Сахалина. Предпочитает чистые горные реки',
    maxSize: 'до 70 см',
    maxWeight: 'до 5 кг',
    lifespan: '3-5 лет',
    origin: 'Древний эндемик Восточной Азии, наиболее близок к предкам тихоокеанских лососей',
    value: 'Редкая и ценная рыба. Мясо с вишневым оттенком. Высокая стоимость',
    nutrition: '195 ккал, 22г белка, 10г жира на 100г',
    facts: [
      'Национальная рыба Японии — символ японской культуры',
      'Может образовывать жилые формы в горных реках',
      'Редкий и охраняемый вид в России',
      'В Японии называется "sakura-masu" — вишневый лосось',
    ],
    status: 'rare',
    category: 'salmon',
  },
  {
    id: 'semga',
    commonName: 'Сёмга',
    scientificName: 'Salmo salar',
    englishName: 'Atlantic Salmon',
    route: '/species/semga',
    image: '/img/species/salmon/species/semga.jpg?v=2',
    imageLarge: '/img/species/salmon/species/semga.jpg?v=2',
    description: 'Атлантический лосось — единственный вид рода Salmo, обитающий в Атлантике. Рыба премиум-класса.',
    habitat: 'Северная часть Атлантического океана, реки Европы, Северной Америки, Балтийское море',
    maxSize: 'до 1.5 метра',
    maxWeight: 'до 40 кг',
    lifespan: '5-8 лет',
    origin: 'Древний вид, отделился от тихоокеанских лососей около 15-20 миллионов лет назад',
    value: 'Премиальное мясо, нежное и жирное. Высокая стоимость. Аквакультурное разведение широко распространено',
    nutrition: '208 ккал, 25г белка, 12г жира на 100г. Высокое качество белка',
    facts: [
      'Единственный атлантический вид лососей',
      'Может нереститься несколько раз в течение жизни',
      'Широко разводится в аквакультуре (Норвегия, Шотландия)',
      'В природе многие популяции находятся под угрозой',
    ],
    status: 'rare',
    category: 'salmon',
  },
];

export const sturgeonSpecies: FishSpecies[] = [
  {
    id: 'beluga',
    commonName: 'Белуга',
    scientificName: 'Huso huso',
    englishName: 'Beluga Sturgeon',
    route: '/species/beluga',
    image: '/img/species/sturgeon/species/beluga.jpg',
    imageLarge: '/img/species/sturgeon/species/beluga.jpg',
    description: 'Крупнейший вид осетровых и самая дорогая икра в мире. Редчайшая рыба, находящаяся под угрозой исчезновения.',
    habitat: 'Каспийское, Черное, Азовское моря. Реки Волга, Дон, Дунай, Днепр',
    maxSize: 'до 5 метров',
    maxWeight: 'до 1500 кг (рекорд 1571 кг)',
    lifespan: 'до 100 лет',
    origin: 'Древнейший вид осетровых, существует более 200 миллионов лет. Пережил динозавров',
    value: 'Самая дорогая икра в мире (до $100,000 за кг). Крупные икринки (3-3.5 мм), маслянистый вкус',
    nutrition: 'Икра: 264 ккал, 28г белка, 17г жира. Мясо: 160 ккал, 20г белка, 9г жира',
    facts: [
      'Крупнейшая пресноводная рыба в мире — может достигать 1.5 тонны',
      'Может жить до 100 лет',
      'Икра белуги — самая дорогая в мире (до $100,000 за килограмм)',
      'В природе практически исчезла, разводится только на аквакультурных фермах',
      'Первый нерест происходит в возрасте 15-20 лет',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
  {
    id: 'kaluga',
    commonName: 'Калуга',
    scientificName: 'Huso dauricus',
    englishName: 'Kaluga Sturgeon',
    route: '/species/kaluga',
    image: '/img/species/sturgeon/species/kaluga.jpg',
    imageLarge: '/img/species/sturgeon/species/kaluga.jpg',
    description: 'Дальневосточный гигант, близкий родственник белуги. Крупнейший осетр Амура.',
    habitat: 'Река Амур и её притоки, Охотское море, Татарский пролив',
    maxSize: 'до 5.5 метров',
    maxWeight: 'до 1000 кг',
    lifespan: 'до 80 лет',
    origin: 'Эндемик бассейна Амура. Эволюционировала отдельно от каспийских осетров',
    value: 'Икра близка к белужьей по качеству, но дешевле. Крупные икринки (2.8-3.2 мм)',
    nutrition: 'Икра: 258 ккал, 27г белка, 16г жира. Высокое содержание Омега-3',
    facts: [
      'Крупнейший осетр Амура — может достигать 5.5 метров',
      'Дальневосточный аналог белуги',
      'Икра калуги высоко ценится и стоит дешевле белужьей',
      'Находится под строгой охраной в России',
      'Разводится на аквакультурных фермах Дальнего Востока',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
  {
    id: 'russian-sturgeon',
    commonName: 'Русский осетр',
    scientificName: 'Acipenser gueldenstaedtii',
    englishName: 'Russian Sturgeon',
    route: '/species/russian-sturgeon',
    image: '/img/species/sturgeon/species/russian-sturgeon.jpg',
    imageLarge: '/img/species/sturgeon/species/russian-sturgeon.jpg',
    description: 'Классический каспийский осетр. Источник традиционной черной икры. Статусный вид.',
    habitat: 'Каспийское, Черное, Азовское моря. Реки Волга, Урал, Дон, Дунай',
    maxSize: 'до 2.5 метров',
    maxWeight: 'до 115 кг',
    lifespan: 'до 50 лет',
    origin: 'Каспийский эндемик, эволюционировал в изоляции Каспийского моря',
    value: 'Классическая черная икра. Средние икринки (2.5-3.0 мм), насыщенный йодистый вкус',
    nutrition: 'Икра: 252 ккал, 28г белка, 15г жира. Мясо: 163 ккал, 21г белка, 8г жира',
    facts: [
      'Источник классической черной икры',
      'Символ каспийского рыболовства',
      'Первый нерест в 8-14 лет',
      'В природе находится под угрозой, разводится на фермах',
      'Может образовывать гибриды с другими осетрами',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
  {
    id: 'siberian-sturgeon',
    commonName: 'Сибирский осетр',
    scientificName: 'Acipenser baerii',
    englishName: 'Siberian Sturgeon',
    route: '/species/siberian-sturgeon',
    image: '/img/species/sturgeon/species/siberian-sturgeon.jpg',
    imageLarge: '/img/species/sturgeon/species/siberian-sturgeon.jpg',
    description: 'Пресноводный осетр Сибири. Самый популярный вид для аквакультуры. Доступная черная икра.',
    habitat: 'Реки Сибири: Обь, Енисей, Лена, Байкал. Может быть полностью пресноводным',
    maxSize: 'до 2 метров',
    maxWeight: 'до 65 кг',
    lifespan: 'до 60 лет',
    origin: 'Пресноводный вид, адаптировавшийся к жизни в реках Сибири',
    value: 'Самая доступная черная икра. Деликатный вкус, средние икринки (2.5-2.8 мм)',
    nutrition: 'Икра: 248 ккал, 27г белка, 14г жира. Мягкий ореховый вкус',
    facts: [
      'Самый популярный вид для аквакультуры',
      'Может быть полностью пресноводным (не нуждается в море)',
      'Быстрее растет в аквакультуре, чем другие осетры',
      'Икра сибирского осетра — самая доступная черная икра',
      'Хорошо адаптируется к разведению',
    ],
    status: 'rare',
    category: 'sturgeon',
  },
  {
    id: 'sevruga',
    commonName: 'Севрюга',
    scientificName: 'Acipenser stellatus',
    englishName: 'Sevruga / Starry Sturgeon',
    route: '/species/sevruga',
    image: '/img/species/sturgeon/species/sevruga.jpg',
    imageLarge: '/img/species/sturgeon/species/sevruga.jpg',
    description: 'Мелкий каспийский осетр с характерным длинным носом. Традиционная севрюжья икра.',
    habitat: 'Каспийское, Черное, Азовское моря. Реки Волга, Урал, Дон',
    maxSize: 'до 2.2 метра',
    maxWeight: 'до 80 кг',
    lifespan: 'до 35 лет',
    origin: 'Каспийский вид, адаптировался к мелководным местам обитания',
    value: 'Мелкая упругая икра (2.0-2.5 мм) с интенсивным вкусом. Традиционная каспийская',
    nutrition: 'Икра: 246 ккал, 26г белка, 13г жира. Упругая текстура',
    facts: [
      'Характерный длинный нос (рострум) — до 60% длины тела',
      'Мелкая, но упругая икра с интенсивным вкусом',
      'Первый нерест в 7-12 лет',
      'Традиционная севрюжья икра — классика каспийской кухни',
      'Быстрее растет, чем другие осетры',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
  {
    id: 'sterlet',
    commonName: 'Стерлядь',
    scientificName: 'Acipenser ruthenus',
    englishName: 'Sterlet',
    route: '/species/sterlet',
    image: '/img/species/sturgeon/species/sterlet.jpg',
    imageLarge: '/img/species/sturgeon/species/sterlet.jpg',
    description: 'Самая мелкая осетровая рыба. Царская рыба России. Пресноводный вид.',
    habitat: 'Реки России: Волга, Дон, Обь, Енисей, Днепр. Чистые пресные воды',
    maxSize: 'до 1.2 метра',
    maxWeight: 'до 16 кг',
    lifespan: 'до 30 лет',
    origin: 'Пресноводный вид, не нуждается в море. Эволюционировал для жизни в реках',
    value: 'Мелкая нежная икра (1.5-2.0 мм). Царская рыба — деликатес',
    nutrition: 'Икра: 240 ккал, 26г белка, 12г жира. Нежный деликатный вкус',
    facts: [
      'Самая мелкая осетровая рыба',
      'Царская рыба России — традиционный деликатес',
      'Пресноводный вид — не нуждается в море',
      'Самый быстрый рост среди осетров',
      'Первый нерест в 4-5 лет',
      'Хорошо разводится в аквакультуре',
    ],
    status: 'rare',
    category: 'sturgeon',
  },
  {
    id: 'amur-sturgeon',
    commonName: 'Амурский осетр',
    scientificName: 'Acipenser schrenckii',
    englishName: 'Amur Sturgeon',
    route: '/species/amur-sturgeon',
    image: '/img/species/sturgeon/species/amur-sturgeon.jpg',
    imageLarge: '/img/species/sturgeon/species/amur-sturgeon.jpg',
    description: 'Эндемик Амура. Средний по размеру осетр с уникальной биологией. Охраняемый вид.',
    habitat: 'Река Амур и её притоки, Охотское море',
    maxSize: 'до 3 метров',
    maxWeight: 'до 190 кг',
    lifespan: 'до 65 лет',
    origin: 'Эндемик бассейна Амура. Эволюционировал в изоляции дальневосточных рек',
    value: 'Редкая икра. Средние икринки (2.5-3.0 мм). Высокая ценность',
    nutrition: 'Икра: 250 ккал, 27г белка, 15г жира',
    facts: [
      'Эндемик бассейна Амура',
      'Находится под строгой охраной',
      'Разводится на аквакультурных фермах Дальнего Востока',
      'Первый нерест в 9-14 лет',
      'Может образовывать гибриды с калугой',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
  {
    id: 'sakhalin-sturgeon',
    commonName: 'Сахалинский осетр',
    scientificName: 'Acipenser mikadoi',
    englishName: 'Sakhalin Sturgeon',
    route: '/species/sakhalin-sturgeon',
    image: '/img/species/sturgeon/species/sakhalin-sturgeon.jpg',
    imageLarge: '/img/species/sturgeon/species/sakhalin-sturgeon.jpg',
    description: 'Редчайший осетр Сахалина. Критически исчезающий вид. Охраняется международным законодательством.',
    habitat: 'Реки Сахалина, Приморья, Хоккайдо, Татарский пролив',
    maxSize: 'до 1.5 метра',
    maxWeight: 'до 60 кг',
    lifespan: 'до 50 лет',
    origin: 'Древний эндемик сахалинских рек. Один из самых редких осетров',
    value: 'Крайне редкая икра. Высокая ценность. Практически не добывается',
    nutrition: 'Икра: 248 ккал, 27г белка, 14г жира',
    facts: [
      'Один из самых редких осетров в мире',
      'Критически исчезающий вид',
      'Охраняется международным законодательством (CITES)',
      'В природе осталось менее 1000 особей',
      'Первый нерест в 12-17 лет',
    ],
    status: 'endangered',
    category: 'sturgeon',
  },
];

export const allFishSpecies = [...salmonSpecies, ...sturgeonSpecies];

